authentication/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    # path('register/',views.register,name='register'),
    # path('login/',views.login,name='login')

    url(r'^register/$',views.register,name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('auth/',include('authentication.urls'))
]

main/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from authentication import  views as auth
from django.conf.urls import url

urlpatterns = [
    path('index',views.index,name='index'),
    path('article/<int:pk>', views.article,name = 'get_article'),
    path('author/<int:pk>', views.author,name = 'get_author'),
    path('article',views.create_article,name = 'create_article'),
    path('author',views.create_author,name = 'create_author'),
    path('',views.home,name = 'home'),
    path('view_authors',views.view_authors,name = 'view_authors'),
    path('search',views.search,name = 'search'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^auth/$',include('authentication.urls')),
    # url(r'^register/$',auth.register,name='register'),
    url(r'^login/$',auth.login,name='login')
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.forms.widgets import Widget
from django.core.exceptions import ValidationError

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=40)
    
    def  __str__(self):
        return self.name

class Article(models.Model):
    title=models.CharField(max_length=50)
    createdAt=models.DateTimeField(auto_now_add=True)
    content=models.TextField()
    authors=models.ManyToManyField('Author')
    category = models.CharField(max_length=255, default="Gaming")

    def __str__(self):
        return self.title

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username',  'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField(max_length = 40)
    password = forms.CharField(widget= forms.PasswordInput)

main/forms.py
from django import forms
from main import models

class CreateAuthor(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

authentication/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from . import forms
from main import models
def register(request):
    loginform = UserCreationForm()
    if request.method == "POST":
        loginform = UserCreationForm(request.POST)
        #if loginform.is_valid():
            #username=loginform.cleaned_data['username']
            #password=loginform.cleaned_data['password1']
            #user = authenticate(username = username,password = password,request= request)
            #if user:
                #HttpResponseRedirect('/')
            #else:
                #pass
        if loginform.is_valid():
            loginform.save()
            username=loginform.cleaned_data['username']
            author_data1 = {
                "name": username
                }
            models.Author.objects.create(**author_data1)
                
            return HttpResponseRedirect('/')
    context ={
        "forms" : loginform 
           }
    return render(request,'auth/register.html',context)

def login(request):
        loginForm =forms.LoginForm()
        if request.method == "POST":
            loginform = forms.LoginForm(request.POST)
            if loginform.is_valid():
                username=loginform.cleaned_data['username']
                password=loginform.cleaned_data['password']
                user = authenticate(username = username,password = password)
                if user:
                    auth_login(request, user)
                    print('logged in')
                    return redirect('/')
                else:
                    print('invalid credentials')
        context ={
            "forms1" : loginForm 
            }
        return render(request,'auth/login.html',context)

main/views.py
from django.shortcuts import render,get_object_or_404
from main import models
from main import forms
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def index(request):
    latest_articles=models.Article.objects.all().order_by('-createdAt')[:20]
    context ={
        "latest_articles":latest_articles
    }
    return render(request,'main/index.html',context)
def article(request,pk):
        article = models.Article.objects.get(pk = pk)
        context= {  
             "article" : article 
        
             }
        return render(request, 'main/article.html',context)

def author(request,pk):
        author = get_object_or_404(models.Author,pk = pk)
        context= {
            "author" : author

        }
        return render(request,'main/author.html',context)

@login_required(login_url='/login/')
def create_article(request):
    authors = models.Author.objects.all()
    context={
            "authors" : authors
    }
    if request.method == "POST":
        article_data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
            "category":request.POST['category']
        }
        article = models.Article.objects.create(**article_data)
        context["success"]=True
    return render(request,'main/create_article.html',context)


def create_author(request):
    create_auth = forms.CreateAuthor()
    if request.method == "POST":
        authorForm = forms.CreateAuthor(request.POST)
        if authorForm.is_valid():
            authorForm.save()
            return HttpResponseRedirect('/article')

    context ={
        "create_auth":create_auth
    }
    #if request.method == "POST":
        #author_data = {
            #"name": request.POST['name']
        #}
        #models.Author.objects.create(**author_data)
        #context["succcess"]=True
    return render(request,'main/create_author.html',context)

def home(request):
    return render(request,'main/home.html')

@login_required(login_url='/login/')
def view_authors(request):
    authors = models.Author.objects.all()
    context={
            "authors" : authors
    }
    return render(request,'main/view_authors.html',context)

@login_required(login_url='/login/')
def search(request):
    if request.method == 'GET':
        searchItem = request.GET.get('search')
        try:
            searchFound = models.Article.objects.filter(category__icontains=searchItem)
            return render(request, 'main/search.html', {"searchItems":searchFound,"term":searchItem}) 
        except:
            return render(request,"main/search.html",{'searchItems':searchFound,"term":searchItem})
    else:
        return render(request, 'main/search.html',{"term":searchItem})

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if forms.non_field_errors %}
  <div class="alert alert-danger" role="alert">

    {% for error in forms.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in forms %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/includes/formlogin.html
{% load form_tags widget_tweaks %}

{% if forms1.non_field_errors %}
  <div class="alert alert-danger" role="alert">

    {% for error in forms1.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in forms1 %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/main/article.html
{% extends 'main/base.html' %}

{% if user.is_authenticated %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     <span><ion-icon class="icon-ion" name="person-circle-outline" size="large"></ion-icon></span> {{ user.username }}
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
      <a class="dropdown-item" href="{% url 'register' %}">Change password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'logout' %}?next=/">Log out</a>
    </div>
  </li>
</ul>
{% else %}
<form class="form-inline ml-auto">
  <a href="{% url 'login' %}" class="btn btn-outline-success mt-2">Log in</a>
  <a href="{% url 'register' %}" class="btn btn-primary ml-2 mt-2">Sign up</a>
</form>
{% endif %}

{% block content %}
<div class="container" id = "header">
    <br><br><br><br><h1 style="text-align:center;">{{ article.title }}</h1>
    <h3 class="lead">Created-At: {{ article.createdAt }}</h3>
    <h4 class="lead">Written By:
        {% for author in article.authors.all %}
            <a href ="{% url 'get_author' author.id %}">
            {{ author }},
            </a>
        {% endfor %}
    </h4>
    <hr style="border: 1px solid black;">
    <div>
        <p class="lead" style="font-size:x-large;line-height:2.5rem;max-width: 100%; white-space: pre-wrap;">
         {{article.content}}          
        </p>
    </div>
</div>

{% endblock %}

templates/main/author.html
{% extends 'main/base.html' %}
{%block content%}
<div id = "head">
   <hr><hr><hr><hr><h1 style="text-align:center;">{{ author.name}}</h1>
    <h4>Articles Written</h4>
    <ul>
        {% for article in author.article_set.all %}
            <li>
                <a href="{% url 'get_article' article.id %}">
                    {{ article }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width-device-width,initial-scale=1.0">
        <meta http-equiv="X-ua-Compartible" content="ie=edge">
        <title>blog application</title>
        <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/post.css' %}">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">My Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Top Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'create_article' %}">Write Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'view_authors' %}">Our Authors</a>
          </li>
          <li class="nav-item">
            <form method="GET" action="{% url 'search' %}" name="form">
              <input type="text" name="search" placeholder="Search"/>
            </form>
          </li>

        </ul>

        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <span><ion-icon class="icon-ion" name="person-circle-outline" size="large"></ion-icon></span> {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'register' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}?next=/">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-success mt-2">Log in</a>
          <a href="{% url 'register' %}" class="btn btn-primary ml-2 mt-2">Sign up</a>
        </form>
      {% endif %}


      </div>

    </div>
  </nav>

    </head>
    <body>
        {% block content %} {% endblock %}

        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>
    </body>

</html>

templates/main/create_article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width-device-width,initial-scale=1.0">
        <meta http-equiv="X-ua-Compartible" content="ie=edge">
        <title>Create Article</title>
        <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Top Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_article' %}">Write Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'view_authors' %}">Our Authors</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <span><ion-icon class="icon-ion" name="person-circle-outline" size="large"></ion-icon></span> {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'register' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}?next=/">Log out</a>
          </div>
        </li>
      </ul>
    {% else %}
      <form class="form-inline ml-auto">
        <a href="{% url 'login' %}" class="btn btn-outline-success mt-2">Log in</a>
        <a href="{% url 'register' %}" class="btn btn-primary ml-2 mt-2">Sign up</a>
      </form>
    {% endif %}
    </div>
  </div>
</nav>
</head>
 <body background="">
  <br><br><br><br><h1 style="text-align:center;"> Create your blog</h1>
    {% if success %}
        <p>Blog created succesfully</p>
    {% endif %}
    
      <form action ="" method="POST" enctype="multipart/form-data">
        <div class="container">
        <div class="form-group">
          {% csrf_token %}
          <input type="text" name="title" class="form-control" placeholder="Enter Title"><br><br>
          </div>
          <textarea style="max-width: 100%;" name="content" class="form-control" placeholder="Content Here"></textarea><br><br>
          <select name="category" class="custom-select mr-sm-2" class="sr-only" required>
            <option value="gaming">Gaming</option>
            <option value="coding">Coding</option>
            <option value="sports">Sports</option>
            <option value="entertainment">Entertainment</option>
          </select>
          <h4 style="text-align:center;">
            <button type="sumbit" class="btn btn-primary mb-2 mt-5">Create</button>
            <button type="reset" class="btn btn-danger mb-2 mt-5">Reset</button></h4>
        </div>
      </div>
      </form>
    
 </body>
</html>






<!--form action="/action_page.php">
    <div class="form-group">
      <label for="email">Email address:</label>
      <input type="email" class="form-control" id="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd">
    </div>
    <div class="checkbox">
      <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form-->
  

templates/main/create_author.html
{% extends 'main/base.html' %}
{% block content %}
<div id = "head1">
    <hr><hr><hr><h1>Create new author</h1>
    <!--{% if success %}
        <p>Author created succesfully</p>
    {% endif %}-->
    <!--form action ="" method="POST"-->
       
            
           <!-- <br><br><br><br><input type="text" class="form-control" name="name" placeholder="put your name here"><br><br>
            <h4 style="text-align:center;"><button type="sumbit" class="btn btn-primary mb-2">Sumbit</button>
            <button type="reset" class="btn btn-primary mb-2">Reset</button></h4>
        </div>
    </form>-->
            <form action ="" method="POST"> 
                <div class="form-group">
                    {% csrf_token %}
                    {{ create_auth }}
                    <h4 style="text-align:center;"><button type="sumbit" class="btn btn-primary mb-2">Submit</button>
                        <button type="reset" class="btn btn-primary mb-2">Reset</button></h4>
                </div>
            </form>


        <p style="text-align:center;"><a href="{% url 'create_article' %}">
            Enter the blogging world
        </a></p>
</div>
{% endblock %}

templates/main/home.html
<!-- Navigation -->
<!--Jai Mata Di-->
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.slim.min.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <span class="sr-only">(current)</span>
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Top Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_article' %}">Write Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'view_authors' %}">Our Authors</a>
        </li>
      </ul>

      {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <span><ion-icon class="icon-ion" name="person-circle-outline" size="large"></ion-icon></span> {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'register' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}?next=/">Log out</a>
          </div>
        </li>
      </ul>
    {% else %}
      <form class="form-inline ml-auto">
        <a href="{% url 'login' %}" class="btn btn-outline-success mt-2">Log in</a>
        <a href="{% url 'register' %}" class="btn btn-primary ml-2 mt-2">Sign up</a>
      </form>
    {% endif %}









    </div>
  </div>
</nav>

<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: url('https://images.wallpaperscraft.com/image/laptop_cup_glasses_plant_114948_2560x1080.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-3">Welcome to My Blog Application </h2>
          <p class="display-4">Here you can write your prespective in your way. .</p>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('http://3.bp.blogspot.com/-4GAiHgbxf8I/Upl3Ff7u6lI/AAAAAAAAOBQ/Ek_A8qzKVao/s1600/Word-Map-Wallpaper-HD-Background-Wallpapers.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class=" text-success display-3">Join millions of other</h2>
          <p class=" text-success display-4"> Share your ideas with millions around worldwide.</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('https://source.unsplash.com/szFUQoyvrxM/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-3 ">What are you waiting for start writing</h2>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>



<!-- Page Content -->
<section class="py-5">
  <div class="container">
    <h1 class="display-4">Contact us </h1>
    <p class="lead">Akshat Jindal-<a target="_blank" href="https://github.com/Akshat809">GitHub</a>, Akash Shukla-<a href="https://unsplash.com/@joannakosinska" target="_blank">Facebook</a>,Abhishek Khnaduri, Mohit Singh Bisht-<a href="https://github.com/Mohitb07" target="_blank">GitHub</a></p>
  </div>
</section>  

templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}



<div class="content container" data-aos="fade-right">
    <div class="row" data-aos="fade-right">
        <div class="col-md-8" data-aos="fade-right">
          <div class="blog_posts" data-aos="fade-right">
          
            {% for post in latest_articles %}
            <div class="jumbotron" style="margin-left: auto;margin-right: auto;margin-top: 11%;" data-aos="fade-right">
            <div class="post">
                <h3><a href="{% url 'get_article' post.pk%}">{{post.title}}</a></h3>
                <div class="">
                    <p>Published on: {{post.createdAt|date:"D, d M, Y"}}</p>
                </div>
                <a href="{% url 'get_article' pk=post.pk %}">Comments : {{post.title}}</a>
            </div>
            <hr style="border: 1px solid black;">
            </div>
        
            {% endfor %}

          </div>

        </div>
    </div>
</div>


{% endblock %}

templates/main/view_authors.html
{% extends 'main/base.html' %}
{% block content %}
<div style = "height: 722px;
background-color: #0093E9;
/*background-image: linear-gradient( #0093E9 0%, #80D0C7 100%);*/
background-image: linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%);">
    <hr><hr><hr><hr><h1>Our Authors</h1>
    <ul>
        {% for author in authors %}
        <li><a href="{% url 'get_author' author.pk %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}